### ISSUE TITLE
Incorrect implementation of the UMD pattern for browser clients

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/css-layout#103]
Currently `main.js` and `Layout.js` implement the UMD pattern based on this variant:

https://github.com/umdjs/umd/blob/master/returnExports.js

However, both implementations have the following lines:

    // Browser globals (root is window)
    root.returnExports = factory(); 

This means that in the absence of an AMD or CommonJS environment, the module will be added as a `returnExports` function on the window object.

When using UMD this property name should be edited!

**Comment by vjeux** [comment]
Agreed :) do it

**Comment by ColinEberhardt** [comment]
> Agreed :) do it

Was that comment meant for #104 ?

I'd like to fix the AMD implementation with a less cut'n'paste oriented approach if possible :-)

**Comment by vjeux** [comment]
Sorry, I just meant that you should do whatever you want to improve the situation :)

**Comment by ColinEberhardt** [comment]
> Sorry, I just meant that you should do whatever you want to improve the situation :)

Thanks - will do :-)
