### ISSUE TITLE
QUESTION: Are the tests in C redundant?

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/css-layout#104]
Just a quick question, the tests in 'C' look like they are all transpiled from the JS tests. Would it be OK if these were removed if the JavaScript tests were run through Travis instead?

I'm just looking to simplify things as much as possible :-)

**Comment by jaredly** [comment]
I like the c tests for confidence that the transpilation process was correct

**Comment by ColinEberhardt** [comment]
> I like the c tests for confidence that the transpilation process was correct

You trust that transpilation was a success based on tests that run through the same transpiler? Is that wise?!

**Comment by vjeux** [comment]
Yeah, we absolutely need C and Java tests. It ensures that the C and Java code we transpile is not completely bogus. There's non-transpiled code that needs to be "integration" tested. It caught a lot of bugs.

**Comment by ColinEberhardt** [comment]
Thanks @jaredly and @vjeux - if they have a history of catching bugs, they are definitely worth keeping :-)
