### ISSUE TITLE
fillNodes should be an optional step

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/css-layout#107]
The current public JS API adapts `computeLayout` to add a fillNodes step, which tramples over any existing `layout` properties, see #62 

I think the public API should make this optional ...

```
computeLayout(..., false); // fillNodes turned off
```

Currently within d3fc we do not use the adapted version of the API.

**Comment by vjeux** [comment]
I don't like boolean arguments. Can you just make fillNodes exist only in the test environment and not expose it outside?

**Comment by ColinEberhardt** [comment]
Hmm ... you're right, think about it boolean args lack discoverability and don't self document.

I'll have a rethink.
