### ISSUE TITLE
Integratation with React

### ISSUE THREAD

**Issue by fsbdev** [facebook/css-layout#115]
The API requires passing a node tree but walking React component tree doesn't give you what you need to pass to this API in one go . Walking through a component's `_renderedChildren` gives you the `node`but not the `props.style`, walking through `props.children` gives you `props.style` but not `node`.

**Comment by paramaggarwal** [comment]
@fsbdev You need to pass the custom formatted tree as mentioned in the docs. You cannot pass a React component hierarchy directly. This is so that it is independent of React.

**Comment by fsbdev** [comment]
Yes, but how can I create that custom tree from the React component tree?

**Comment by paramaggarwal** [comment]
Well you need to walk `props.children` that will give you `props.style` as you mention. That's your tree. Then you can take the output `layout` and set it back on the React component tree. Looks like you are using React outside DOM context?

**Comment by fsbdev** [comment]
Yeah I am. I have a WebGL scene graph instead. How do I set it back on the React component tree as you suggest? My idea was to try and get a reference to each node along with props.style as I'm creating the tree, but that led me to this issue.

**Comment by paramaggarwal** [comment]
So what you'd like is that there is a React component tree with `props.style` like `flexDirection: 'row', flex: 1` etc. that you would like to convert to `top`, `left`, `width`, `height` for use in WebGL.

What you can do is walk React component tree and extract the `props.style` into a tree that css-layout understands. Pass the tree via css-layout to get the rendered `layout` attribute with `top`, `left`, `width`, `height` on the tree. I'm not familiar with WebGL much, but you need to somehow use these `layout` attributes in WebGL now.

**Comment by fsbdev** [comment]
I got it working but I had to save the style objects onto my scene graph nodes too.
Thanks
