### ISSUE TITLE
can css-layout use as a polyfill for flex 2012

### ISSUE THREAD

**Issue by tlightsky** [facebook/css-layout#120]
for example, 
```display:flex``` is not fully supported on some device such as webview on android 4.1
can i use this as a polyfill on that device

**Comment by ColinEberhardt** [comment]
Yes, it could be used as the layout engine for a flexbox polyfill that's a really good idea! You'd have to combine this code with a CSS parser in order to construct the polyfill.

**Comment by tlightsky** [comment]
I want to use it like [this](https://github.com/cgarvis/react-vendor-prefix) in react component.
I think ```computeLayout``` is the key,but how to use this key to fix the wrong layout(browser not support flex 2012)?
```computeLayout``` need a ```nodeTree```,I think that's the whole tree.
but when translate,I can only get part of the whole tree.
Is there any hint?

**Comment by jonathantneal** [comment]
I’m working on a version of flexibility that uses css-layout. So far, it works fantastic.

I’m close to being finished, but I’m still working out a bug (actually I’m not sure if it’s css-layout or my implementation) where a `align-items: stretch; flex-direction: row; flex-wrap: wrap; width: 300px` container corrects stacks its children, but none of them stretch to match height.

Also, and I have no plans to release this, with an Array.prototype.forEach polyfill and an additional calculation for content-box, I saw Flexbox in IE6.

**Comment by jonathantneal** [comment]
The branch is up. https://github.com/10up/flexibility/tree/css-layout

**Comment by jonathantneal** [comment]
@ColinEberhardt, @tlightsky, [Flexibility](https://github.com/10up/flexibility/) is now powered by CSS Layout and it’s working very well.

**Comment by ColinEberhardt** [comment]
That's really cool - nice work @jonathantneal

**Comment by emilsjolander** [comment]
This is still possible by using the JS version from the deprecated branch. Moving forward css-layout will focus on native code as that is where we have seen most usage.
