### ISSUE TITLE
View not stretching vertically in column layout

### ISSUE THREAD

**Issue by brentvatne** [facebook/css-layout#127]
### @corbt said in https://github.com/facebook/react-native/issues/2724#issuecomment-140902710

I think I may have found a couple of inconsistencies that are related to my problem. I've created what I believe are equivalent layouts in React Native and HTML/CSS that appear to demonstrate different flexbox behavior. Am I just crazy or is this a bug?

#### HTML
JSFiddle [here](https://jsfiddle.net/awtLxLpm/)

#### React Native
```jsx
<View style={{flexDirection: 'row', alignItems: 'stretch', width: 150}}>
  <View style={{backgroundColor: 'red'}}>
    <View style={{backgroundColor: 'green'}}>
      <Text style={{backgroundColor: 'purple', alignSelf: 'center'}}>
        Column 1
      </Text>
    </View>
  </View>
  <Text style={{backgroundColor: '#B2DBFF', height: 150}}>Column 2</Text>
</View>
```

Output on my Android device:
![device](https://cloud.githubusercontent.com/assets/176426/9885921/a27e94e6-5bdf-11e5-9b9d-3b1d3405c19e.png)

#### Differences
In React Native the intermediary green `div` doesn't expand to fill the column vertically, and the "Column 1" text is not centered vertically either. On my machine (OS X/Chrome 45) the HTML version does.

**Comment by corbt** [comment]
Update: here's a new [JSFiddle](https://jsfiddle.net/awtLxLpm/1/) using the css-layout default styles and with updated inline styles appear the same as the old version. And the equivalent React Native JSX, which still renders to the image embedded above (tested on Android and iOS simulator):

```jsx
<View style={{flexDirection: 'row', alignItems: 'stretch', width: 150}}>
  <View style={{flexDirection: 'row', backgroundColor: 'red'}}>
    <View style={{flexDirection: 'row', backgroundColor: 'green'}}>
      <View style={{backgroundColor: 'purple', alignSelf: 'center'}}>
        <Text>
          Column 1
        </Text>
      </View>
    </View>
  </View>

  <View style={{backgroundColor: '#B2DBFF', height: 150}}>
    <Text>Column 2</Text>
  </View>
</View>
```

**Comment by brentvatne** [comment]
Hurray, this is pulled into React Native now :) https://github.com/facebook/react-native/commit/d95757037aef3fbd8bb9064e667ea4fea9e5abc1
