### ISSUE TITLE
How to debug or log in javascript test?

### ISSUE THREAD

**Issue by myocytebd** [facebook/css-layout#128]
Or is it possible to provide a standalone html based test driver, so as to eliminate the steep learning curve?

**Comment by ColinEberhardt** [comment]
If you edit the gruntfile you can set `singleRun` to false at the following line:

https://github.com/facebook/css-layout/blob/master/Gruntfile.js#L96

This ensures that the Chrome browser and Karma do not shut down after the test run.

You can run the tests as follows:

    grunt test-javascript

This will launch chrome allowing you to set breakpoints etc ..
