### ISSUE TITLE
how to run java version

### ISSUE THREAD

**Issue by ruanshanshan** [facebook/css-layout#130]
import into java project ,but error with :the import javax.annotation.Nullable cannot be resolved, The import com.facebook.infer cannot be resolved

**Comment by kmagiera** [comment]
You need to add the content of https://github.com/facebook/css-layout/tree/master/src/java/lib to your java classpath

**Comment by ColinEberhardt** [comment]
Better still - use one of the versioned releases:

https://www.npmjs.com/package/css-layout

These contain the JAR file for the Java version.

**Comment by oded-regev** [comment]
Thanks, I'm sure it would help many developers to add short integration instructions for each platform...
