### ISSUE TITLE
Add C# version to the grunt build (and CI)

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/css-layout#142]
Currently the build does the following:

 + Runs static code analysis on the JS code
 + Runs the JS tests
 + Transpiles to Java and runs tests
 + Transpiles to C and runs tests
 + Packages / bundles all of the above.

The CI runs all of the above too.

The C# code is very much absent from this process!

**Comment by ColinEberhardt** [comment]
Update: Thanks to #151 the C# code is now compiled and tested - the only thing missing from CI is the bundling, which in this case is the creation of a DLL.

**Comment by emilsjolander** [comment]
Build process has changed so closing this. C# version will be integrated into buck build process as well.

**Comment by ColinEberhardt** [comment]
Cool, I did notice that some big changes were on their way. 

Can I just check, will the new build still wanted regular releases to npm? My project, and a number of others, depend on this!

**Comment by emilsjolander** [comment]
If the community wants native binaries through npm then that is definitely something we will look into continuing to do. The JS version has been removed though. The reason behind removing the JS version was that it was not used internally and the web supports flexbox very well nowadays. css-layout targets native platforms so it makes more sense that the source of truth be C.

**Comment by ColinEberhardt** [comment]
Actually it isn't the native binaries that I was wanting to have distributed through npm, it's the JavaScript code. While the web supports flex box, there are still a number of interesting / novel uses for this JavaScript implementation.

For example, we use it within [d3fc](http://d3fc.io) to bring flex box to SVG, as described in [this blog post](http://blog.scottlogic.com/2015/02/02/svg-layout-flexbox.html). There are a few other projects that use this code too:

https://libraries.io/npm/css-layout/dependents

I presume the new implementation is C rather than JS? I can understand the reasoning for this.

I'd just suggest not withdrawing css-layout from npm (although I guess that as I was the one who published it, I'd be the one that would have to remove it!)

**Comment by emilsjolander** [comment]
Yeah I don't see a great reason to remove what is already on npm :) It
would be interesting to look into using emscripten to generate a js version
from the c code for use in these kinds of projects. Nothing I am
prioritizing but I would definitely be interested in seeing a pull request
for that if you would find that useful :)
