### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by devongovett** [facebook/css-layout#149]
Last npm release was in September, but some changes have happened since then. Can someone release a new version to npm? Thanks!

**Comment by vjeux** [comment]
cc @ColinEberhardt

**Comment by ColinEberhardt** [comment]
Good call - yes, it's been a while. I'll take a look at this tonight or tomorrow morning :-)

**Comment by ColinEberhardt** [comment]
Done: 

https://github.com/facebook/css-layout/releases/tag/v1.1.0

You'll also find this release up on npm. Would be great to get #142 resolved so that the C# API is properly managed also.

**Comment by devongovett** [comment]
Looks like dist/css-layout.js didn't get rebuilt before the release. It still has the old code.

**Comment by ColinEberhardt** [comment]
@devongovett thanks for the heads-up, I've published v1.1.1 that should fix this.

I clearly need to do a bit more work on the process, I'll update shortly!
