### ISSUE TITLE
Padding on parent container interacting strangely with absolute positioned child

### ISSUE THREAD

**Issue by brentvatne** [facebook/css-layout#152]
Original issue: https://github.com/facebook/react-native/issues/4240#issuecomment-158357783

You can see it in action here: https://rnplay.org/apps/gtEDqA

Notice that the child view with the light-blue background is being given a width equal to screen width minus 2x the padding. Seems related to #74, but changing the parent container to absolute positioning doesn't fix it.

**Comment by emilsjolander** [comment]
rnplay link no longer works. This issue is pretty old and A lot of code has changed since then. Please re-open if this is still an issue and include a new repro.

**Comment by edi** [comment]
This is surely an issue :)

I've just encountered it now, on 0.64 (using expo's latest SDK).
