### ISSUE TITLE
Port to Swift

### ISSUE THREAD

**Issue by darknoon** [facebook/css-layout#158]
I'm interested in messing around with building a swift version of css-layout. Just opening this issue to make sure I'm not duplicating work with anyone else.

I started hacking on it based on the c# code, since they're the most similar pair of languages. There are some unique challenges in figuring out the best type definition since swift lacks fixed-sized arrays (and you can't index a tuple by an `Int`).

Anyway, does anyone have interest in this?

**Comment by vjeux** [comment]
If you get it working, I'll gladly merge it :)

**Comment by darknoon** [comment]
Thanks @vjeux. I probably have a few more hours of hacking to get it all to compile, then I need to figure out how to run the tests from grunt, etc.

**Comment by alexdrone** [comment]
This repo contains a wrapper for swift.
https://github.com/alexdrone/FlexboxLayout

**Comment by ColinEberhardt** [comment]
@alexdrone - so that is a wrapper around the C implementation rather than transpiling the code into native Swift?

**Comment by alexdrone** [comment]
Yes exactly.. interoperability between C and swift is really great, and you can simply wrap the C structs and funcs with swift ones.
Have a look at https://github.com/alexdrone/FlexboxLayout/blob/master/FlexboxLayout/Layout.swift

**Comment by emilsjolander** [comment]
closing this. I'm happy to accept a pull request for C bindings to swift though :)
