### ISSUE TITLE
LayoutEngine 183 test problem

### ISSUE THREAD

**Issue by NekR** [facebook/css-layout#164]
Hi guys, I am porting this library to Haxe (mostly manually changing syntax from Java to Haxe) and everything seems okay expect of `testCase183()` (the last) which fails with this diff: https://www.diffchecker.com/lpkicsai (Left: Actual; Right: Expected).

I am very new to this library, so it's very hard for me to find right place where I should look for the error. Any ideas why it may happen?

**Comment by vjeux** [comment]
the way I usually debug that is to put bunch of console.logs and run that test and see where things get different and figure out why :)

**Comment by NekR** [comment]
@vjeux, yeah, this is what I am doing now :)

**Comment by vjeux** [comment]
This is pretty cool that you are working on that :)

**Comment by NekR** [comment]
Okay, I found it. It was a difference in loops and that library uses iteration variable (`ii`) out of scope of `for`. Hexe doesn't have standard `for` loop (`for (;;;)`) but only `for (i in from...to)`. Anyway, it's fixed now :)

@vjeux Yep, it is. I just needed layout engine in a game I am working on, so `css-layout` is easier way to make it. But now I think.. why you may need it in JS and then transpile with hack to other langs, why not having one codebase and compiling to whatever you need?

**Comment by vjeux** [comment]
It's unfortunately pretty hard to write things in different languages and interop nicely. For css-layout, the dom structure is in the host language and there's a parallel css structure that needs to be maintained so it's easier in one language.

To support obj-c, it's pretty easy to write it in C, but for js having to transpile with emscriptem is very annoying and I don't really want to have the overhead of jni for the java version.

In the end, this solution even though feels hacky works really well in practice :)

**Comment by NekR** [comment]
@vjeux I mean Haxe here, which is not most popular language of course, but it can compiler to what ever you want. And I understand that it's easier write JS, especially for for quick prototypes. And that compiled version (from universal) language could have (and probably have) some performance issues. But it looks nice to me that I can now use `css-layout` in C game and test it in JS with node like this: 

`haxe -cp ./Source -main Tests -js ./TestsOutput/tests.js && node ./TestsOutput/tests.js`

:)

**Comment by vjeux** [comment]
Yeah, if you implement the haxe version then we'll have many more for free :)

**Comment by NekR** [comment]
Need to port `CSSNodeTest` and `LayoutCachingTest` and then it's done. I will create new issues as soon as it's ready :)

**Comment by lucasr** [comment]
Keep in mind that the Java transpiler doesn't do a direct translation from JS to Java. It also applies several Android-specific optimizations around avoiding method invocations as much as possible. Whatever general solution we end up using here will have allow for language-specific optimizations for css-layout.

**Comment by NekR** [comment]
@lucasr Yes, it's understandable. I am looking now at generated Java code and I am not sure if I like it. But I am not a Java expert, so may be things are not that bad there.

**Comment by lucasr** [comment]
@NekR Yeah, the generated Java code is extra verbose but that's intentional. We've done some aggressive method inlining (among other things) to improve performance on Android (see #120, #121, #122).

**Comment by NekR** [comment]
@lucasr I meant generated from Haxe version, your Java handwritten + generated seems fine. I can provide/show generated Java code from Haxe if you do not want build it yourself :) If you are interested of course.
