### ISSUE TITLE
Port to Haxe

### ISSUE THREAD

**Issue by NekR** [facebook/css-layout#165]
Hey, here it is: https://github.com/NekR/css-layout-haxe

It's not based on a latest repo commit though, but rather on a latest commit at a time of forking `css-layout` here https://github.com/NekR/css-layout (`4 commits behind facebook:master` at the moment). So some updates should be added, I think.

I tested it with JS and Java and everything works fine, I mean that tests pass.
To test on JS run `sh tests.sh`, for Java and any other lang it will look like this:

```
haxelib install hxjava
haxe -cp ./src -main Tests -java ./_tests_output/tests_java
java -jar ./_tests_output/tests_java/Tests.jar
```

Hope this port will be helpful :)

**Comment by NekR** [comment]
A bit more info -- it's ported from Java code with little modifications, e.g. `layoutContext` is removed and `measure()` uses real functions (Haxe functions) instead of Java-specific way.
So in case of JS, it compiles same type of code -- with constants, enums, etc. and as far as I understand, you need it in a bit different format to test agains Chrome's implementation, so wrapper probably is required here.

In case of other languages, it may generated not best code, because it's compiled from "universal" lang. So some language-specific injections might be required too to make it as good as real Java code, for example.

**Comment by NekR** [comment]
Okay, it's up-to-date now.

Anyway, not sure about usefulness of this port for you, because it turns out that Haxe adds its runtime to the generated code. So, it's probably always will be slower than pure-lang-code.

**Comment by emilsjolander** [comment]
Closing this. Feel free to submit a pull request with the port based on the latest master. I'm not sure we want to support it in the main repo due to maintenance costs but i'm open to it if there is a strong Haxe community that would like to use css-layout.
