### ISSUE TITLE
Supported Attributes

### ISSUE THREAD

**Issue by jonathantneal** [facebook/css-layout#167]
I’d like to better understand your supported attributes.

You list `flex` as a [supported attribute](https://github.com/facebook/css-layout#supported-attributes) which accepts a positive number, but the [`flex`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) property is a shorthand for 3 properties; `flex-grow`, `flex-shrink`, and `flex-basis`. Does this mean `flex` is actually `flex-grow`, or would you explain how this property should be used?

You do not list `alignContent` as a supported attribute, but [appears to be supported](https://github.com/facebook/css-layout/blob/master/dist/css-layout.js#L302-L307). Is this partial support, or should I open a PR to update the README.md?

**Comment by emilsjolander** [comment]
alignContent is being exposed. Regarding flex we currently only support a simplified flex model. We plan to expand this to support flex-grow, flex-shrink, and flex-basis as separate properties.
