### ISSUE TITLE
Flex with min-width

### ISSUE THREAD

**Issue by jonathantneal** [facebook/css-layout#168]
Using `flex` and `min-width` together cause an unexpected horizontal overflow.

I have created a (vertical) side-by-side comparison. http://s.codepen.io/jonneal/debug/WrXEbM ( source: http://codepen.io/jonneal/pen/WrXEbM )

Also, the vertical stretching of items looks like `align-content: stretch` is in play rather than the [expected default](https://github.com/facebook/css-layout#default-values) of `align-content: flex-start`.

**Comment by sahrens** [comment]
Is this still an issue? Seems like you might need to use flex wrap to get what you want. cc @vjeux, @lucasr
