### ISSUE TITLE
When flex:1, padding working wrong way

### ISSUE THREAD

**Issue by xueduany** [facebook/css-layout#173]
![image](https://cloud.githubusercontent.com/assets/1139866/13768931/62c5cbec-eab6-11e5-8f24-6d4376542039.png)
![image](https://cloud.githubusercontent.com/assets/1139866/13768938/76068368-eab6-11e5-84c0-2380f050a755.png)
![image](https://cloud.githubusercontent.com/assets/1139866/13768945/9209b97c-eab6-11e5-9a68-357f1fd3c9d4.png)
when padding 4 direction all working ,it goes wrong way, double padding left distance,not working at padding right

**Comment by emilsjolander** [comment]
Works as expected now.
