### ISSUE TITLE
Chat panel

### ISSUE THREAD

**Issue by abhishekmedipta** [facebook/css-layout#179]
There is a bug in facebook in chat, there is a chat panel in right side of facebook page, when there are lots of people are online and that time, if we scroll the scroll bar, then last user are not showing properly.

see the attachment..

![screenshot 100](https://cloud.githubusercontent.com/assets/16331239/14066446/f1a7f6dc-f466-11e5-9677-ba7ea45b224f.png)
![screenshot 100 _3](https://cloud.githubusercontent.com/assets/16331239/14066447/f1aa99a0-f466-11e5-96bb-fd467fb3db9f.png)

**Comment by javache** [comment]
Hi @abhishekmedipta,

This is not a channel to report Facebook bugs. Please follow the instructions on https://www.facebook.com/help/186570224871049 to report this issue.
