### ISSUE TITLE
Question about "default values" listed on README.md

### ISSUE THREAD

**Issue by ericmasiello** [facebook/css-layout#180]
On the README, it lists part of the default styling as for RN components as:

```
...
align-content: flex-start;
...
```
Am I wrong or do you actually mean:

```
justify-content: flex-start;
```

**Comment by vjeux** [comment]
No, this is actually align-content. The default is `stretch` and we want to make it `flex-start` instead. If you look at the spec, `justify-content` default is already `flex-start`.
