### ISSUE TITLE
What does `flex` actually do?

### ISSUE THREAD

**Issue by ericmasiello** [facebook/css-layout#181]
In CSS, `flex` is just a shorthand for `flex-grow`, `flex-shrink`, and `flex-basis`. Since none of these properties exist in React Native, what does the `flex` property actually mean?

**Comment by vjeux** [comment]
See the spec for flex: https://developer.mozilla.org/en-US/docs/Web/CSS/flex

If you have only one value, it means flex-grow:

/* One value, unitless number: flex-grow */
flex: 2;

**Comment by ericmasiello** [comment]
Thanks! Are there plans to adopt `flex-shrink` or `flex-basis` at any point or were they deemed unnecessary?

**Comment by vjeux** [comment]
The general thoughts when supporting a new feature in the project is that by default we don't, but if there are common use cases where this would be useful, then we should consider it. We don't want to support every css property in the world, but don't want to leave out useful ones either :)

I haven't heard many people saying that flex-basis and flex-shrink would be useful in the context of a react native app though.

**Comment by ericmasiello** [comment]
Fair. Just curious. Thanks again @vjeux!
