### ISSUE TITLE
margin: auto w/ flex elements

### ISSUE THREAD

**Issue by awendland** [facebook/css-layout#198]
As mentioned in PR #185, the current implementation does not allow for `margin` to be set to `auto`. It would be great to have this support to open the possibilities of much more complex flex based layouts which can handle variable screen sizes and child content sizes.

Is this portion of the spec on the roadmap for implementation? Or is it considered outside of desired compliance because it would add too much complexity to the code base?

**Comment by emilsjolander** [comment]
For now it has been considered outside of the scope we want to handle. However I'm open to convincing arguments for why it would be useful. We have yet to need to make use of it. Could you provide one or more concrete examples of where it would enable a layout which is hard / impossible within the current api?

**Comment by awendland** [comment]
Our use case no longer needs `margin: auto`. Thanks for the fast response!

**Comment by kkga** [comment]
> Could you provide one or more concrete examples of where it would enable a layout which is hard / impossible within the current api?

`margin: auto` behavior for flex items is quite useful in various cases: basically it's the only way to manipulate placement of a flex item along the main flex axis.

Here's a very basic example: https://jsbin.com/jajamus/edit?html,css,output

More on this here: https://medium.com/@samserif/flexbox-s-best-kept-secret-bd3d892826b6#.wrp6m8bwx

**Comment by dopcn** [comment]
@emilsjolander Can you share with us how would you manipulate placement of a flex item along the main flex axis in yoga?  It seems using `margin: auto` is pretty big deal when doing this.

Reference: http://stackoverflow.com/questions/32551291/in-css-flexbox-why-are-there-no-justify-items-and-justify-self-properties

**Comment by emilsjolander** [comment]
Could you provide some concrete examples of a layout you wish to implement?
