### ISSUE TITLE
Facebook>Chat panel

### ISSUE THREAD

**Issue by abhishekmedipta** [facebook/css-layout#208]
There is a bug in facebook in chat, there is a chat panel in right side of facebook page, when there are lots of people are online and that time, if we scroll the scroll bar, then last user are not showing properly.

see the attachment..

![screenshot 100](https://cloud.githubusercontent.com/assets/16331239/14066344/a7891240-f464-11e5-9fe5-056cfe4a8257.png)

![screenshot 100 _3](https://cloud.githubusercontent.com/assets/16331239/14066341/92487e98-f464-11e5-8465-28729df8ad49.png)

**Comment by emilsjolander** [comment]
Please keep this project's issues related to the project. While we appreciate bug reports regarding facebook this is not the correct forum for them. Thank you.

**Comment by abhishekmedipta** [comment]
@emilsjolander So can u please tell me correct forum...

**Comment by emilsjolander** [comment]
https://www.facebook.com/help/326603310765065
