### ISSUE TITLE
Why the default flex-direction is CSS_FLEX_DIRECTION_COLUMN

### ISSUE THREAD

**Issue by hustwcw** [facebook/css-layout#209]
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction
In this mozilla specification, the initial value for flex-direction should be "row". Why the implementation in css-layout is "column" in init_css_node function?

**Comment by emilsjolander** [comment]
While we try to stick to the specification in most cases, especially when it comes to the implementation of the algorithm we have chosen to change the default values to values we thought were more sensible / common when developing mobile UIs. I see a future where we might have two init_css_node functions. One with the defaults specified in the w3c specification and one with the default we have found work best for us. No timeline on this though but I would happily accept a pull request which implemented this.
