### ISSUE TITLE
JavaScript variant planned?

### ISSUE THREAD

**Issue by queequac** [facebook/css-layout#215]
Just some question: In the past css-layout was written in JavaScript and transpiled to C.
Now C seems to be the primary language the library is written in.

Are there any plans to do the same vice-versa again, transpiling this time to JavaScript?
Otherwise I am stuck to the deprecated version, while it was the big advantange of css-layout having really identical behavior in both languages.

**Comment by emilsjolander** [comment]
Let me start with some backstory on the change. The js version was not used by us internally and working with the regex transpilation process slowed us down. The libraries focus was to bring flexbox to mobile and in reaching that goal js is not important. That said I know of many reasons why a js version is important and would be useful so if we could solve that with little to no development overhead I would be all for it. One way I can think of doing this is via emscripten (http://kripken.github.io/emscripten-site/index.html). 

I won't personally be working on this in the near future as there are more pressing issues (for us) to solve. However I would love community contribution here.
