### ISSUE TITLE
Adding .NET support

### ISSUE THREAD

**Issue by mpodwysocki** [facebook/css-layout#219]
Currently working on the .NET Support for the CSSLayout in the ReactWindows org on the [dotnet branch](https://github.com/ReactWindows/css-layout/tree/dotnet).  Feedback welcome!

**Comment by browniefed** [comment]
Didn't the C# version get added at some point, https://github.com/facebook/css-layout/pull/129?
(I vaguely follow css-layout was just curious)

**Comment by emilsjolander** [comment]
Thank you so much, this is awesome! Could you open this as a pull-request instead of an issue? It makes it much easier to see what was added/removed/changed :) 

@browniefed It was temporarily removed during the current re-structuring to use C as the source of truth language.
