### ISSUE TITLE
Chrome vs. Safari compatibility for flex-wrap:wrap

### ISSUE THREAD

**Issue by jordwalke** [facebook/css-layout#227]
Here's one of the test cases. Note that there is no width.

```html
 <div id="wrap_column" style="height: 100px; flex-wrap: wrap">
   <div style="height: 30px; width: 30px;"></div>
   <div style="height: 30px; width: 30px;"></div>
   <div style="height: 30px; width: 30px;"></div>
   <div style="height: 30px; width: 30px;"></div>
 </div>
```

When I run this on chrome, the total width ends up being `30px`. When I run it in Safari, it ends up occupying whatever width is available (the document.body width).

When I run the layout algorithm, the total width ends up being 60. That is also what the test case ensures:
https://github.com/facebook/css-layout/blob/1f300a58fb263685ffab17b66665a79f5acd09f4/tests/CSSLayoutFlexWrapTest.cpp#L79

Which one is correct?

**Comment by emilsjolander** [comment]
There is a comment in the top of this file describing this problem.

**Comment by jordwalke** [comment]
Ah, sorry I missed that.
