### ISSUE TITLE
Question about reasons to deprecate pure Java version?

### ISSUE THREAD

**Issue by Bobris** [facebook/css-layout#228]
JNI version is faster? Or it was just too big burden to maintain? Is there possibility to resurrect its development in future?

**Comment by emilsjolander** [comment]
JNI version is significantly faster and maintaining two copies of the algorithm was painful and led to slowed development speed. Java is still fully supported and a major use case of css-layout just from now on it should be used via the JNI wrapper provided. If you have any problems using it via JNI please file a separate issue and I'll make sure to help to the best of my ability 👍
