### ISSUE TITLE
Releases / semver

### ISSUE THREAD

**Issue by gimenete** [facebook/css-layout#240]
Hi,

I'm going to use this library in a new project and I'm wondering if there's any plan to release versions of it using semver versioning, so we are aware of possible breaking changes, or determine if a version si stable or not.

Thanks,

**Comment by emilsjolander** [comment]
The master branch will almost always be stable in terms of not crashing, compiling etc. However the API might not be (in practice though it almost never changes). We have plans to introduce versioning soon though!

**Comment by gimenete** [comment]
Good to know about the stability of the `master` branch. And glad to hear that you have plans to introduce versioning.

Feel free to close the issue or keep it open until you introduce versioning.

Thanks!
