### ISSUE TITLE
Clear ownership of an object

### ISSUE THREAD

**Issue by yunxing** [facebook/css-layout#244]
Discussed with @emilsjolander offline. The suggest ownership of an object should always be the creator of the object. However, `CSSNodeFreeRecursive` somehow broke this by assuming the ownership of the children are now to the tree itself. This confusion can very easily lead to memory leaks like in https://github.com/facebook/css-layout/blob/e00e30ca150b3212457bac3e4efd9e22383001ad/tests/CSSLayoutDirtyMarkingTest.cpp#L89, where it is unclear who should be the one to call free on "node0"

I'm thinking there are two things we can do:
1. Add comments on the API to make clear about who is the ownership of an object.
2. Add comments on the `CSSNodeFreeRecursive` API to discourage people from using it, as it confuses people.

I can do the change if it sounds good to people.

**Comment by yunxing** [comment]
cc @emilsjolander @jordwalke

**Comment by emilsjolander** [comment]
`CSSNodeFreeRecursive` should be seen as a convenience function, it does not in any way indicate ownership of a node is the tree itself. The creator of the node is responsible of freeing the node, in this case if the creator of the node is the same as creator of the whole tree (often times in tests for example) then `CSSNodeFreeRecursive` is a convenience over calling `CSSNodeFree` on all nodes individually.

**Comment by yunxing** [comment]
@emilsjolander That makes sense now, thanks!
