### ISSUE TITLE
Support center alignment with CSSPositionTypeAbsolute

### ISSUE THREAD

**Issue by yihuang** [facebook/css-layout#266]
It would be quite useful to me if we support align center with ``CSSPositionTypeAbsolute``, with this we can mix flexbox and ``AutoresizingMask`` style layout.
If you are also interested in this, I've willing to implement this.

EDIT: I'm using css-layout in a ui system of 2d game engine, trying to replace old layout system with flexbox, for backward compatibility, I need to re-implement old system with css-layout, and I've successfully re-implemented most of it with ``CSSPositionTypeAbsolute`` mode except center aligning.

**Comment by woehrl01** [comment]
Small hint: With #258 I introduced CSSUnit which could be extended for ```auto```. So you could uses  ```margin-left: auto``` to center your elements.

**Comment by emilsjolander** [comment]
@yihuang I'm pretty sure absolute positioned elements on the web cannot be centered so I'm skeptical on supporting it in this library. There is however a super simple work around you can do.

psuedo code:
```html
<div style="width: 500px; height: 500px;">
  <!-- Absolute layout container with single centered child -->
  <div style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; justify-content: center; align-items: center;">
    <!-- Child you want to align center in absolute layout -->
    <div style="..."></div>
  </div>
</div>
```

@woehrl01 I would rather avoid supporting `margin-left: auto` for centering as it it a rather arcane concept from css. Better to have true alignment primitives.

**Comment by woehrl01** [comment]
@emilsjolander agree

**Comment by yihuang** [comment]
How about this, add two fields: ``center-left/center-top`` which means:
```
left=(parent_width-self_width) / 2 + center-left
top=(parent_height-self_height) / 2 + center-top
```

Which only has effect with absolute position type, when left/top is not specified.

**Comment by emilsjolander** [comment]
For now you should be able to use the work around I provided, this should also be easy to wrap into some abstraction within your application. I would rather not add specific alignment properties for absolute layout although if it ends up being highly requested we can look into it again.
