### ISSUE TITLE
How does it fit into React?

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/css-layout#36]
Any exmaples by now? I don't think such grammar is easy to be used in React:

```js
computeLayout(
  {style: {padding: 50}, children: [
    {style: {padding: 10, alignSelf: 'stretch'}}
  ]}
);
// =>
{width: 120, height: 120, top: 0, left: 0, children: [
  {width: 20, height: 20, top: 50, left: 50}
]}
```

**Comment by jdkanani** [comment]
I think it would be useful in React Native.

**Comment by vjeux** [comment]
This is a low level implementation in a separate phase in React Native. It cannot be used with React directly :(

**Comment by nick** [comment]
are there plans to add support eventually?

**Comment by jlongster** [comment]
This isn't really that useful on the web. There's a key component missing, which is measuring width/height of text. Until that happens, we can't really do manually layout.

**Comment by nick** [comment]
I was thinking of using it for a 2 column layout with a fixed header, footer and left column. I suppose there's not much point in only 'half' implementing the spec though.

**Comment by haihappen** [comment]
I would love to use css-layout in my projects as a fallback for IE's lacking support of flexbox. Any chance to do this?

**Comment by jlongster** [comment]
You might be able to get away with it if you never need to use `flex: 0`. If you use `flex: 0`, you need to calculate the width/height of the box based on contents, which this library does not help with. The web doesn't help either. Native platforms have measurement APIs.

**Comment by vjeux** [comment]
@jlongster this is not entierely true. You can measure text by creating dom nodes and measuring them in an iframe but it's prohibitely slow. There's the canvas api that's faster but doesn't do line breaks so you've got to hack around it. There isn't any in a web worker.

So, it's not that there is no text measurement api, it's more like none of the existing ones are good eno

**Comment by fdecampredon** [comment]
stupid question, why not using a canvas measureText ability ? :p

**Comment by vjeux** [comment]
@fdexampredon: the problem with measureText is that it doesn't handle text wrapping :(((

**Comment by fdecampredon** [comment]
Could we not just compute textWrapping manually ?
In my previous company we had to use similar technique to use text wrapping  with svg.
We used unicode linebreak algorithm + measureText, and the result was not bad.

**Comment by fdecampredon** [comment]
We event thought about computing that in a web-worker with embedded font + font parser (and so no measureText) but It was a bit complex so we ended up never trying it ^^.

**Comment by vjeux** [comment]
We absolutely could :)

**Comment by fdecampredon** [comment]
Ok I think i need to try that :p, any advice ?
