### ISSUE TITLE
flexStart is same as flexEnd

### ISSUE THREAD

**Issue by jlongster** [facebook/css-layout#38]
I noticed this while playing around with my live editor. Check this out: http://layout.jlongster.com/#node%2528%250A%2520%2520%257B%2520padding%253A%252050%252C%2520flexDirection%253A%2520%2527column%2527%2520%257D%252C%250A%2520%2520%2520node%2528%257B%2520padding%253A%252010%2520%257D%2529%252C%250A%2520%2520%2520node%2528%257B%2520padding%253A%252010%252C%2520alignSelf%253A%2520%2527flexStart%2527%2520%257D%2529%252C%250A%2520%2520%2520node%2528%257B%2520padding%253A%252010%252C%2520alignSelf%253A%2520%2527center%2527%2520%257D%2529%252C%250A%2520%2520%2520node%2528%257B%2520padding%253A%252010%252C%2520alignSelf%253A%2520%2527flexEnd%2527%2520%257D%2529%250A%2529

The elements with `flexStart` and `flexEnd` are the same. Shouldn't `flexStart` be all the way to the left, not the right?

Edit: if you want to see how I use the lib, see https://github.com/jlongster/live-css-layout/blob/master/static/js/render.js

**Comment by vjeux** [comment]
It's `flex-end` not `flexEnd` :)

We have warnings for that in react-native
