### ISSUE TITLE
Nested children bug?

### ISSUE THREAD

**Issue by jlongster** [facebook/css-layout#39]
Look at this: http://layout.jlongster.com/#node%2528%250A%2520%2520%257B%2520padding%253A%252050%252C%2520flexDirection%253A%2520%2527column%2527%2520%257D%252C%250A%2520%2520%2520node%2528%257B%2520padding%253A%252010%2520%257D%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520node%2528%257B%2520padding%253A%252010%2520%257D%2529%2529%250A%2529

The boxes should be nested, not outside of each other, right?

**Comment by vjeux** [comment]
This is the result of the layout algorithm, it looks correct to me. I feel like there's something wrong with your bindings.

```javascript
  it('should layout text with flexDirection column', function() {
    testLayout(
      {style: {padding: 50, flexDirection: 'column'}, children: [
        {style: {padding: 10}, children: [
          {style: {padding: 10}}
        ]}
      ]},
      {width: 140, height: 140, top: 0, left: 0, children: [
        {width: 40, height: 40, top: 50, left: 50, children: [
          {width: 20, height: 20, top: 10, left: 10}
        ]}
      ]}
    );
  });
```

**Comment by vjeux** [comment]
I also tried with a container with a fixed size, and gives me the same good looking result

```javascript
  it('should layout text with flexDirection column', function() {
    testLayout(
      {style: {width: 1000}, children: [
        {style: {padding: 50, flexDirection: 'column'}, children: [
          {style: {padding: 10}, children: [
            {style: {padding: 10}}
          ]}
        ]}
      ]},
      {width: 1000, height: 140, top: 0, left: 0, children: [
        {width: 1000, height: 140, top: 0, left: 0, children: [
          {width: 900, height: 40, top: 50, left: 50, children: [
            {width: 880, height: 20, top: 10, left: 10}
          ]}
        ]}
      ]}
    );
  });
```

**Comment by jlongster** [comment]
Oh, is the top/left relative to the parent? That would make more sense!

**Comment by vjeux** [comment]
Yup, relative to the parent :)

**Comment by jlongster** [comment]
Awesome, fixed on my end, thanks!
