### ISSUE TITLE
must run examples in Chrome

### ISSUE THREAD

**Issue by nickdesaulniers** [facebook/css-layout#46]
From the readme:
> For the JS tests: Open RunLayoutTests.html and RunLayoutRandomTests.html in Chrome

I'm curious, why do the examples/tests depend on one browser?

**Comment by vjeux** [comment]
Mostly because I only needed to test it against one implementation to make sure that it is correct.

@ryanseddon made the test suite run on Firefox as well, but apparently there are still some failing tests. Need to investigate what's going on
https://github.com/facebook/css-layout/pull/43
