### ISSUE TITLE
Polyfill

### ISSUE THREAD

**Issue by oravecz** [facebook/css-layout#51]
Is there potential for a flexbox polyfill for IE8 and IE9 (and IE10)?

**Comment by lynndylanhurley** [comment]
I'm wondering this as well.

#52 says that it works on "every browser out there", but that sounds kind of insane.

@vjeux - can you confirm that this will work with IE8 and IE9?

**Comment by RangerMauve** [comment]
This won't style the page for you, but it'd totally be possible to write a polyfill that's based on this library.

**Comment by lynndylanhurley** [comment]
@RangerMauve - thanks, I think I may have misunderstood the goals of this project.

Just to be clear, is it safe to say that this project is meant to provide flexbox layouts to native environments (iOS, Android), and not to serve as a flexbox polyfill for browsers?

**Comment by RangerMauve** [comment]
It's not bound to native at all, it just doesn't change the style of DOM nodes for you.

What it does do is compute the different sizing of elements given some CSS rules that use flexbox. If one wants to then use that sizing to render native stuff they can. If they wanted to, they could also use it to update the styles of DOM nodes in the browser.

But out of the box it just does calculations
