### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by jimmyhmiller** [facebook/css-layout#53]
Looks like I might finally get some time to work on my project using css-layout. And of course I can clone it to use the updated js api. But, it would be nice if the npm package was updated.

Thanks for the awesome work on react and this library.

**Comment by RangerMauve** [comment]
Yeah, I ended up cloning the repo to work with it. But because of that I can't safely release any modules that use this.

**Comment by vjeux** [comment]
Just pushed 0.0.2, sorry about the delay

**Comment by RangerMauve** [comment]
Thank you!
