### ISSUE TITLE
Does this handle text?

### ISSUE THREAD

**Issue by RangerMauve** [facebook/css-layout#54]
The example in the JSFiddle seems to imply that `<Text>` tags automatically size based on their content, but I don't see text content being mentioned in the [supported attributes](https://github.com/facebook/css-layout#supported-attributes)

Could you clarify how this library should be used when the size of the text content is not known in advance?

**Comment by vjeux** [comment]
You need to provide a `measure` function in order to measure text. Unfortunately, there is no clean API on the web to measure text so you have to hack around.

You can take a look at
https://github.com/facebook/css-layout/blob/master/src/Layout-test-utils.js#L321-L351
for an example, but it's suuupppeerrr slow

**Comment by RangerMauve** [comment]
Ah, expected as much.

I was thinking that if I limited myself to supporting monospaced fonts, it'd be easy enough to do it in two passes.

Basically, run over the layout as if there was no text content, then look at the heights and widths that got computed, then for places, where the height should be varying, calculate the number of lines that would exist based on how many characters fit into the width.

Does this sound reasonable, or is it also too inefficient?

**Comment by RangerMauve** [comment]
Seems this was also discussed in #36

**Comment by RangerMauve** [comment]
Is text supported now? Or was this just cleanup?

**Comment by vjeux** [comment]
Oops sorry, I'm cleaning up the issue queue. I don't have any plans of implementing it, but if you are interested, I may consider a pull request

**Comment by RangerMauve** [comment]
Cool. Thanks for the clarification!

**Comment by anql** [comment]
https://github.com/facebook/css-layout/blob/master/src/Layout-test-utils.js#L321-L351
```
404 NOT FOUND
```
