### ISSUE TITLE
Contents stop respecting parent's top

### ISSUE THREAD

**Issue by RangerMauve** [facebook/css-layout#55]
I've made a small renderer for turning the generated boxes into an SVG image, and it seems that children within one of my elements keep being positioned relative to the top of the image, rather than the top of their parent.

Specifically, in my [example](http://rangermauve.github.io/css-layout-render/example/), the `content` element's children keep being positioned relative to the top. Their `width` and `height` seem to be working properly, but the `top` and `left` aren't.

I've tried fiddling with the style extensively: removing the flex from them `content` and setting a height on the children, removing the elements beside `content`, changing the `flexDirection`, and it keeps happening.

The weird part is that the `header` element seems to be working properly.

Any idea what might be up? Is my input just malformed, or is this a bug?

(You can change the JSON in the textarea and click `update` to re-render)

**Comment by vjeux** [comment]
Note that the position is relative to the parent, if you want to display it relative to the root, you need to manually accumulate all the positions. Does it make sense?

**Comment by RangerMauve** [comment]
Oh! I hadn't realized that. Thanks for clearing it up!
