### ISSUE TITLE
Percentage widths and heights

### ISSUE THREAD

**Issue by mrjjwright** [facebook/css-layout#57]
Hi,  this is an awesome library and I wrapped it easily in Objective-C and am loving the easy layout.  One thing I ran into today, my third day with the lib, was how to update the bounding box of a layout when it's used in a different situation since the library doesn't support percentage based widths?  E.g, an orientation change.  How to specify that a layout should fill it's container at 100%?  Is there a simple heuristic you all use in React Native or elsewhere for this?  I assume I can recurse into the layout and update the widths and heights manually as I need but just want to make sure that I get your official position before I think about this too much.

**Comment by vjeux** [comment]
flex: 1 is probably what you want. It is the equivalent of height: 100%

There's also alignItems: 'stretch' which is the default and width: 100%.

Note that if you have flexDirection: 'row', the axis is inverted for the two above

**Comment by mrjjwright** [comment]
Ok, looks like a rookie question, all I need to do is make sure the containers that need to be "responsive" have these properties, makes total sense.  Thanks @vjeux!

**Comment by jasalo** [comment]
What about trying to get a <View> elemtn to fill a third of the parent's or the "window's" width, something like
{width: '33%'}
So far it doesn't seem possible, as it only parses the String into Integers.
Any workaround you guys know?

**Comment by vjeux** [comment]
You can use flex for that

```
<View>
  <View style={{flex: 1}} />
  <View style={{flex: 2}} />
</View>
```

The first view is going to take up 1/(1+2) and the second is going to take up 2/(1+2) of the parent

**Comment by nickhudkins** [comment]
What about... 80% width, centered.

Is: 

<View>
    <View style={{flex: .1}} />
    <View style={{flex: .8}} />
    <View style={{flex: .1}} />
</View>

the only way possible?

**Comment by plrthink** [comment]
How to solve this problem (http://stackoverflow.com/questions/18744164/flex-box-align-last-row-to-grid) without percentage value support?

**Comment by DaniAkash** [comment]
If we need to specify height and width respective to screen size of the device instead of size of the parent component, flex won't be enough. 

**[react-native-responsive-dimensions](https://www.npmjs.com/package/react-native-responsive-dimensions)** can specify height, width and fontSize with percentage respective to device's screen size.
