### ISSUE TITLE
fillNodes overwrites the layout and children properties

### ISSUE THREAD

**Issue by esprehn** [facebook/css-layout#62]
If node already has a layout object it should leave it alone, this just means allocating new Rect like objects each time this is called even if layout has been done before.

Also if you define node.style.measure it clears the children property, but that's bad if the measure function wanted to be able to look at the children or call layout on them.

**Comment by vjeux** [comment]
Please feel free to send a pull request for this :) The js version has not been designed with performance in mind, only the C one
