### ISSUE TITLE
measure should be on node, not style.

### ISSUE THREAD

**Issue by esprehn** [facebook/css-layout#63]
The measure callback seems to be designed for text, but the text is stored in the node itself not in the style of a node, which means to use the node.style.measure callback you need to create a new closure for every node that reflects back to the node's value.

node.style.measure = function(width) {
  var text = node.textContent;
  return measureText(text, width);
};

instead if the method was placed on node itself you wouldn't need a closure for every node which is better for memory usage and startup performance.

Node.prototype.measure = function(width) {
  return measureText(this.textContent, width);
};

**Comment by vjeux** [comment]
Please send a pull request if that's something you want to see. This seems like a good idea

**Comment by emilsjolander** [comment]
The measure function does exist on the node and not the style now. Closing this.
