### ISSUE TITLE
Style checks force code to go polymorphic or worse

### ISSUE THREAD

**Issue by esprehn** [facebook/css-layout#64]
width/height/top/left use isDimDefined and isPosDefined which checks for undefined. margin and padding properties use the "in" operator which isn't fast and also means you need to totally omit those properties from your object if you want them to have "no value" for layout.

ex.
```js
if (pos in node.style) {
    return node.style[pos];
}
return 0;
```

should just be return node.style[pos] || 0;

For getSpacing it should do:

```js
return node.style[key] || node.style[type + suffix] || 0;
```

This means your style object can have that property all the time and just use the value undefined to get the default. The current code forces you to have many different "types" of Style objects which makes v8 and other JS engines go slow.

**Comment by vjeux** [comment]
Totally! The js version has not been written with performance in mind. If you send a pull request i'd gladly accept it :)

**Comment by JonSonesen** [comment]
Hey!
Noticed that this has been sitting for a while and would like to go ahead and implement these optimizations. I can get started right away but want to make sure that @esprehn didn't already tackle this so as to avoid redundancy. I am a CS student who couldn't find an internship this summer so I saved up money to take the summer off and do as much work on open source projects as I can handle. :)

**Comment by vjeux** [comment]
Please send out pull requests :)

**Comment by JonSonesen** [comment]
:+1:

**Comment by jaredly** [comment]
@JonathonSonesen were you going to PR with those fixes?

**Comment by JonathonSonesen** [comment]
Hi Jared, after running the tests I found that there were no notable
performance improvements from my changes so I closed the pull request also,
I am not very experienced so I wasn't sure what I had done was even
correct. I started a summer class and its an accelerated course so my time
has been filled with calculus 2 for the last 7 weeks in addition to doing
udemy courses for js and python. I can definitely reopen the pull request
if you'd like to see what I added.  My final is next Wed. so I can take
another look at it after I wrap that up as well.

**Comment by jaredly** [comment]
Ok cool :) good luck with finals

**Comment by JonathonSonesen** [comment]
Thanks man! I plan to slay them, with the sweet knowledge blades I've been forging ;)

**Comment by emilsjolander** [comment]
Js version is gone, closing this.
