### ISSUE TITLE
Children items are not vertically aligned properly when the height of the parent is undefined

### ISSUE THREAD

**Issue by delimy** [facebook/css-layout#83]
```
Sample input:
{  
  style:{  
    flexDirection:"row"
  },
  children:[  
    {  
      style:{  
        width:100,
        flexDirection:"row"
      },
      children:[  
        {  
          style:{  
            width:20,
            height:20,
            alignSelf:"flex-end"
          }
        }
      ]
    },
    {  
      style:{  
        width:100,
        height:200
      }
    }
  ]
}

```
"flex-end" in the sample is not doing anything.

**Comment by delimy** [comment]
correct:
![screen shot 2015-05-08 at 6 37 44 pm](https://cloud.githubusercontent.com/assets/6600721/7548110/6e70cdf2-f5b1-11e4-9a79-1f28fdb59110.png)
wrong:
![screen shot 2015-05-08 at 6 38 06 pm](https://cloud.githubusercontent.com/assets/6600721/7548113/74ad8d2c-f5b1-11e4-9fc2-7c37e62a443a.png)

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by dubert** [comment]
:+1:

**Comment by swathysubhash** [comment]
Facing this issue

**Comment by rreusser** [comment]
We may be experiencing a very similar issue in which flex properties have no effect unless the width is explicitly defined. In other words, centering is basically impossible unless the width is explicitly set. This could be solved if `width:100%` were possible, but that's a separate (but again, related?) issue.

**Comment by respectTheCode** [comment]
+1
