### ISSUE TITLE
Support for percentage width/height for cross-axis dimension?

### ISSUE THREAD

**Issue by lynaghk** [facebook/css-layout#93]
Currently only pixels are supported for lengths (e.g., min-height, max-height, height).
While flex can be used to handle percentage-like calculations along the primary axis (see #57 #27), there's currently no way to do percentage-like calculations along the cross-axis. (Just `align-items: stretch` on the parent, which corresponds to `width: 100%` or `height: 100%` on the child.)

Would ya'll be open to a pull request adding percentage support?
If so, is there a writeup of the code architecture/algorithm beyond the source?

**Comment by spicyj** [comment]
I don't think we have any philosophical objection. There's a fair amount of interest here: https://github.com/facebook/react-native/issues/364. No extra docs as far as I know of.

**Comment by lynaghk** [comment]
I'll take a look at the existing code and see if I can figure out what'd be necessary to add percentage support. I'm currently evaluating some other options (using a browser for CSS calculations or implementing flexbox calcs in ClojureScript) so I can't estimate if/when I'll get to this --- good to know it's philosophically in the clear, though = )

**Comment by tlightsky** [comment]
@lynaghk have you implement a cljs version?
I want to make a polyfill for flex2012 in older browser I think I can use some cljs version :)

**Comment by lynaghk** [comment]
No, not yet. Still potentially on the horizon, but likely not for another 6
months.

On Wed, Oct 14, 2015 at 12:25 AM, tlightsky <notifications@github.com>
wrote:

> @lynaghk <https://github.com/lynaghk> have you implement a cljs version?
> I want to make a polyfill for flex2012 in older browser I think I can use
> some cljs version :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/css-layout/issues/93#issuecomment-147960828>.
>



-- 
Kevin Lynagh
Keming Labs

*http://keminglabs.com <http://keminglabs.com>*888.502.1042

**Comment by emilsjolander** [comment]
Closing this. I'm happy to merge a pull request that implements % based width / height. I don't think it should be limited to the cross axis if implemented though and instead work like it does on the web. This has some perf concerns though.

**Comment by Venryx** [comment]
It appears this has now been implemented: https://github.com/facebook/react-native/commit/3f49e743bea730907066677c7cbfbb1260677d11
